drupal-vget, tests

diff --git a/bin/drupal-vget b/bin/drupal-vget
--- a/bin/drupal-vget
+++ b/bin/drupal-vget
@@ -18,4 +18,34 @@ Usage: {0} var_name"
 
 check_drupal
 
-drupal-sql "SELECT value FROM {variable} WHERE name='$1'" | drupal-decode
+check_sql="SELECT COUNT(*) FROM {variable} WHERE name='$1'"
+if [ -n "$SCRIPT_VERBOSE" ]; then
+	result=$(drupal-sql -v "$check_sql")
+else
+	result=$(drupal-sql "$check_sql")
+fi
+
+if [ "$result" -eq 0 ]; then
+	echo >&2 "variable '$1' not found"
+	exit 1
+fi
+
+sql="SELECT value FROM {variable} WHERE name='$1'"
+if [ -n "$SCRIPT_VERBOSE" ]; then
+	result=$(drupal-sql -v "$sql")
+else
+	result=$(drupal-sql "$sql")
+fi
+
+if [ $? -ne 0 ]; then
+	echo ""
+	exit 1
+fi
+
+if [ -n "$result" ]; then
+	result=$(drupal-decode "$result")
+fi
+if [ "$result" = "true" ]; then result=1; fi
+if [ "$result" = "false" ]; then result=0; fi
+
+echo "$result"
