drupal-patch, tests

diff --git a/bin/drupal-patch b/bin/drupal-patch
--- a/bin/drupal-patch
+++ b/bin/drupal-patch
@@ -13,21 +13,35 @@ Usage: {0} (path_file|path_url)"
 
 check_drupal
 
+if [ -z "$1" ]; then
+	usage
+	exit 1
+fi
+
 src="$1"
-path_name="drupal.patch"
+patch_name="drupal.patch"
 rej_name="patch.rej"
+trap 'rm -f "$patch_name" "$rej_name"' EXIT
 
 if [ -f "$src" ]; then
 	#echo "copy patch from $src"
-	cp "$src" "$path_name"
+	cp "$src" "$patch_name"
 else
 	#echo "download patch $src"
-	wget -q -O "$path_name" "$src" > /dev/null
+	wget -q -O "$patch_name" "$src" > /dev/null
 fi
 
-patch --strip=1 --force --silent --reject-file="$rej_name" < "$path_name"
+if [ ! -f "$patch_name" ]; then
+	echo "patch $patch_name not exists"
+	exit 1
+fi
 
-rm "$path_name"
+patch --strip=1 --force --silent --reject-file="$rej_name" < "$patch_name"
+
+if [ $? -ne 0 ]; then
+	echo "patch error"
+	exit 1
+fi
 
 log_text="$(date '+%Y-%m-%d %H:%M'); $PWD; $src"
 
@@ -35,17 +49,15 @@ if [ -f "$rej_name" ]; then
 	# patch rejected
 	echo "$log_text; patch failed"
 
-
 	# не знаю, как не создавать бекапы, поэтому при неудаче удаляем бекапы, созданные за последнюю минуту
 	# и файл .rej
 	find -cmin -1 -name "*.orig" -exec rm {} \;
-	rm "$rej_name"
 	exit 1
 else
 	# patch success
 	echo "$log_text; patch success"
 
-	# файлы при патче меняют владельца, меняем его назад
+	# change owner of patched files
 	if [ $(whoami) = "root" ]; then
 		user=$(stat -c '%U' $(pwd))
 		find -mmin -1 -exec chown $user:$user {} \;
