drupal-vget, removed 1 of 2 sql queries

diff --git a/commands/drupal-vget b/commands/drupal-vget
--- a/commands/drupal-vget
+++ b/commands/drupal-vget
@@ -26,23 +26,6 @@ fi
 
 check_drupal
 
-check_sql="SELECT COUNT(*) FROM {variable} WHERE name='$1'"
-if [ -n "$SCRIPT_VERBOSE" ]; then
-	result=$(drs sql -v "$check_sql")
-else
-	result=$(drs sql "$check_sql")
-fi
-
-if [ "$result" = "error" ]; then
-	echo >&2 "sql error"
-	exit 1
-fi
-
-if [ "$result" -eq 0 ]; then
-	echo >&2 "variable '$1' not found"
-	exit 1
-fi
-
 sql="SELECT value FROM {variable} WHERE name='$1'"
 if [ -n "$SCRIPT_VERBOSE" ]; then
 	result=$(drs sql -v "$sql")
@@ -50,7 +33,13 @@ else
 	result=$(drs sql "$sql")
 fi
 
+if [ -z "$result" ]; then
+	echo >&2 "variable '$1' not found"
+	exit 1
+fi
+
 if [ $? -ne 0 ]; then
+	echo >&2 "sql error"
 	exit 1
 fi
 
