cron-add, detect drs path at runtime

diff --git a/commands/drupal-cron-add b/commands/drupal-cron-add
--- a/commands/drupal-cron-add
+++ b/commands/drupal-cron-add
@@ -20,8 +20,10 @@ Options:
 check_drush
 check_drupal
 
-if [ ! -r "$DRUPAL_SCRIPTS_BINARY" ]; then
-	echo >&2 "Script '$DRUPAL_SCRIPTS_BINARY' not found, aborting."
+DRS_BINARY="$(which drs)"
+
+if [ ! -r "$DRS_BINARY" ]; then
+	echo >&2 "Script '$DRS_BINARY' not found, aborting."
 	exit 1
 fi
 
@@ -33,7 +35,7 @@ trap 'rm -f "$temp_file"' EXIT
 
 crontab -l -u "$user" > "$temp_file" 2>/dev/null
 
-cron_command="$DRUPAL_SCRIPTS_BINARY cron-run \"$root_path\""
+cron_command="$DRS_BINARY cron-run \"$root_path\""
 
 if [ -n "$(grep "$cron_command" "$temp_file")" ]; then
 	echo >&2 "drush was in cron, exit"
