fix tests, correct exitcodes and error output

diff --git a/commands/drupal-module-doc b/commands/drupal-module-doc
--- a/commands/drupal-module-doc
+++ b/commands/drupal-module-doc
@@ -10,12 +10,19 @@ Usage: {0}
         - output whole docs file
 
        {0} module_name
-        - output lines about module"
+        - output lines about module
+
+       {0} module_name docs_file
+        - output lines about module from docs_file"
 
 . $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init
 
+if [ -n "$2" ]; then
+	DOCS_FILE="$2"
+fi
+
 if [ ! -r "$DOCS_FILE" ]; then
-	echo "DOCS_FILE $DOCS_FILE not found"
+	echo >&2 "DOCS_FILE $DOCS_FILE not found"
 	exit 1
 fi
 
diff --git a/commands/drupal-patch b/commands/drupal-patch
--- a/commands/drupal-patch
+++ b/commands/drupal-patch
@@ -32,14 +32,14 @@ else
 fi
 
 if [ ! -f "$patch_name" ]; then
-	echo "patch $patch_name not exists"
+	echo >&2 "patch $patch_name not exists"
 	exit 1
 fi
 
 patch --strip=1 --force --silent --reject-file="$rej_name" < "$patch_name"
 
 if [ $? -ne 0 ]; then
-	echo "patch error"
+	echo >&2 "patch error"
 	exit 1
 fi
 
