drs, command wrapper
Rewrite scripts, directory structure and help.
Now, all scripts shoulkd run through drs

diff --git a/commands/drupal-cron-add b/commands/drupal-cron-add
--- a/commands/drupal-cron-add
+++ b/commands/drupal-cron-add
@@ -15,10 +15,15 @@ Cron job add to user-owner of root_path.
 Options:
         -s Simulate mode, don't actually change the system"
 
-. drupal-scripts-init
+. $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../lib/drupal-scripts-init
 
 check_drush
 check_drupal
+
+if [ ! -r "$DRUPAL_SCRIPTS_BINARY" ]; then
+	echo >&2 "Script '$DRUPAL_SCRIPTS_BINARY' not found, aborting."
+	exit 1
+fi
 
 root_path="$PWD"
 user=$(stat -c '%U' "$root_path")
@@ -28,7 +33,7 @@ trap 'rm -f "$temp_file"' EXIT
 
 crontab -l -u "$user" > "$temp_file" 2>/dev/null
 
-cron_command="$DRUPAL_SCRIPTS_ROOT/drupal-cron-run \"$root_path\""
+cron_command="$DRUPAL_SCRIPTS_BINARY cron-run \"$root_path\""
 
 if [ -n "$(grep "$cron_command" "$temp_file")" ]; then
 	echo "drush was in cron, exit"
